 platform :ios, '12.0'

target 'RandomUsers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RandomUsers
pod 'Alamofire'
pod 'PromisedFuture'
pod 'SwiftyJSON'
pod 'NVActivityIndicatorView'
pod 'Kingfisher'
end
